#!/bin/sh

if [ $# -gt 1 ]
then
	echo "Too many arguements (expecting 0 or 1)" >&2
	exit 1
elif [ $# -eq 1 ]
then
	i=0
	token=''
	while [ $i -lt $1 ]
	do
		token="$token "
		i=$(($i + 1))
	done
else
	token='	'
fi

sed "s/$token//"