#!/bin/sh
host=$1

echo $(basename $0): requesting confirmation >&2
/usr/local/bin/sshfs -o IdentityFile="$HOME/.ssh/id_ed25519_sk" -o uid=501 -o gid=501 root@${host}:/ "$HOME/n/${host}"

if [ $? -ne 0 ]
then
	echo $(basename $0): connection failed >&2
	exit
else
	echo $(basename $0): connection successful >&2
fi

#trap "/sbin/umount \"$HOME/n/${host}\"; exit" EXIT INT TERM

while true
do
	sleep 10
done
