#!/bin/sh
# Assumes the user can run cat and tee as root without a password

if type doas >/dev/null 2>&1
then
	sudo=doas
else
	sudo=sudo
fi

if [ $# -eq 0 ]
then
	fname=$(9p read acme/$winid/tag | awk '{ print $1 }')
	9p read acme/$winid/body | $sudo /usr/bin/tee $fname >/dev/null 2>&1
	echo clean | 9p write acme/$winid/ctl
else
	if echo $1 | grep -E '^/' > /dev/null 2>&1
	then
		fname=$1
	else
		fname=$(pwd)/$1
	fi
	echo name $fname | 9p write acme/new/ctl
	winid=$(9p read acme/index | awk '{ print $1 " " $6 }' | grep $fname | awk '{ print $1 }')
	echo -n 'Sudo ' | 9p write acme/$winid/tag
	$sudo /bin/cat $fname | 9p write acme/$winid/body
	echo clean | 9p write acme/$winid/ctl
fi
