alias ll="ls -l"
alias la="ls -A"
alias lla="ls -lA"
alias tas="tmux attach-session -t"
alias tns="tmux new-session -s"
alias tls="tmux list-sessions"
alias ts="tmux-session"
alias psh="pass show"
alias pc="pass -c"
alias pls="pass ls"
alias feh="feh --auto-rotate --scale-down"
alias rsync="rsync -C --include=.git/"
alias ag="ag -p ~/.cvsignore"
alias pacupdates="cat /run/motd.pacman"
alias psu="ps -U $LOGNAME"
