#!/bin/sh
__clone()
{
    echo "Cloning $1"
    git clone https://github.com/$1 > /dev/null 2>&1
}

if [ -d bundle/start -o -d bundle/opt ]
then
    echo "bundle/start or bundle/opt already exists. Aborting." > 2
    exit 1
fi

# Plugins that should always be enabled
mkdir -p bundle/start
cd bundle/start
__clone romainl/Apprentice
__clone tpope/vim-commentary
__clone tpope/vim-eunuch
__clone tpope/vim-fugitive
__clone tpope/vim-obsession
__clone tpope/vim-scriptease
__clone tpope/vim-surround
__clone tpope/vim-unimpaired
__clone tpope/vim-vinegar
__clone Raimondi/delimitMate
__clone junegunn/goyo.vim
__clone junegunn/limelight.vim
__clone ajh17/VimCompletesMe
__clone skammer/vim-css-color
__clone ludovicchabant/vim-gutentags
__clone beloglazov/vim-online-thesaurus
__clone jszakmeister/vim-togglecursor
cd - > /dev/null 2>&1

# Plugins used optionally
mkdir -p bundle/opt
cd bundle/opt
__clone jpalardy/vim-slime
cd - > /dev/null 2>&1

unset __clone
