-- Eight-color scheme
local lexers = vis.lexers
-- djmoch
lexers.STYLE_DEFAULT      = ''
lexers.STYLE_NOTHING      = ''
lexers.STYLE_CLASS        = ''
lexers.STYLE_COMMENT      = ''
lexers.STYLE_CONSTANT     = ''
lexers.STYLE_DEFINITION   = ''
lexers.STYLE_ERROR        = ''
lexers.STYLE_FUNCTION     = ''
lexers.STYLE_KEYWORD      = ''
lexers.STYLE_LABEL        = ''
lexers.STYLE_NUMBER       = ''
lexers.STYLE_OPERATOR     = ''
lexers.STYLE_REGEX        = ''
lexers.STYLE_STRING       = ''
lexers.STYLE_PREPROCESSOR = ''
lexers.STYLE_TAG          = ''
lexers.STYLE_TYPE         = ''
lexers.STYLE_VARIABLE     = ''
lexers.STYLE_WHITESPACE   = ''
lexers.STYLE_EMBEDDED     = ''
lexers.STYLE_IDENTIFIER   = ''

lexers.STYLE_LINENUMBER        = 'fore:yellow'
lexers.STYLE_LINENUMBER_CURSOR = lexers.STYLE_LINENUMBER
lexers.STYLE_CURSOR            = 'reverse'
lexers.STYLE_CURSOR_PRIMARY    = lexers.STYLE_CURSOR..',fore:yellow'
lexers.STYLE_CURSOR_LINE       = 'underlined'
lexers.STYLE_COLOR_COLUMN      = 'back:red'
lexers.STYLE_SELECTION         = 'back:white'
lexers.STYLE_STATUS            = 'back:black,fore:blue,bold'
lexers.STYLE_STATUS_FOCUSED    = 'back:blue,fore:white,bold'
lexers.STYLE_SEPARATOR         = lexers.STYLE_DEFAULT
lexers.STYLE_INFO              = 'fore:default,back:default,bold'
lexers.STYLE_EOF               = 'fore:blue'
