#!/bin/bash
update()
{
    echo "Updating $1"
    cd $1
    git pull
    cd - > /dev/null
}

export -f update
cd bundle/opt/
ls -1d */ | xargs -n 1 -P 10 -I {} bash -c 'update "$@"' _ {}
cd -
cd bundle/start/
ls -1d */ | xargs -n 1 -P 10 -I {} bash -c 'update "$@"' _ {}
cd -
