#!/bin/sh
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | ctags --tag-relative=yes --output-format=e-ctags -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
