if type brew > /dev/null 2>&1
then
	HOMEBREW_NO_ANALYTICS=1
	HOMEBREW_NO_INSECURE_REDIRECT=1
	HOMEBREW_CASK_OPTS=--require-sha\ --appdir="$HOME/Applications"
	HOMEBREW_NO_AUTO_UPDATE=1
	export HOMEBREW_NO_ANALYTICS HOMEBREW_NO_INSECURE_REDIRECT
	export HOMEBREW_CASK_OPTS HOMEBREW_NO_AUTO_UPDATE
	__addpath "`brew --prefix`/bin" "before"
fi
